### ISSUE TITLE
Feedback about Saved Sessions

### ISSUE THREAD

**Issue by GHNeko** [AterialDawn/ApexParse#1]
![Apex](http://puu.sh/DFGvH/2a8943312a.png)
![Over](http://puu.sh/DFGvY/3f67c76812.png)

Tons of spacing between the sections. Also Apex logs damage taken as apart of the parse.  ![Spacing](http://puu.sh/DFGyX/7603b5b61a.png)

I suggest the spacing be removed since the formatting is feels unnecessary and that damage taken either be removed since it's already tracked in the header anyways.

Seems like Apex also is missing total damage and total dps as well as the duration of the encounter.

![Apex](http://puu.sh/DFGC9/800e63b447.png)
![Over](http://puu.sh/DFGBZ/014b505f37.png)

**Comment by AterialDawn** [comment]
Spacing was left as-is, but total damage, dps, and encounter duration was added into Release 10
