### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GHNeko** [AterialDawn/ApexParse#2]
I had wanted to bring up 2 suggestions.

1. When looking at the detailed breakdown for a player's performance within APEX, there is a lack of a column for DPS. I feel that adding a DPS column when looking at a per-move breakdown of one's DPS is fairly useful for helping one assess which moves to use and why.

2. There is a "Hide All Other Players" option in Overparse that would be significantly more useful for posting parses in public while protecting other players IF the parse would change dynamically with the option. If you enable the option before hand, and disable it, the parse doesn't change; and vise versa with the same result. This is probably because the option simply prevents other players from being recorded during the session. Having Hide All Other Players simply hide what's displayed rather than ignoring recording them would be useful for the purpose of hiding other players performance. Anonymizing names only goes so far as people can still poke fun at other players in the parse even if there is no name attached to them.

2.5. To follow the trails of 2, allowing the user to toggle their character's name from (Name) to (YOU) as per the original/old versions of overparse from way back when would also be useful for anonymity (though it would better allow people to "pose" as another player).

**Comment by AterialDawn** [comment]
Name anonymization and DPS column added into Release 10
