### ISSUE TITLE
Input Delay while Apex is Open

### ISSUE THREAD

**Issue by GHNeko** [AterialDawn/ApexParse#3]
This has happened twice total so far, but the 1st time I wasn't 100% sure APEX was the source, but this time I've fairly sure. I went into XH FF to practice some stuff and a boss spawned. While I was in the middle of the fight, my inputs were being dropped heavily and/or were delayed by a few seconds.  I wasn't sure what was going on at the time, so I simply disconnected and reconnected my controller as I thought it was Steam and/or DS4 acting up, but that didnt solve the issue. I then remembered what happened last time and I solved it by closing Overparse and APEX and my issue when away when reopening. However this time, instead of closing APEX, I decided to simply end the session and the problem went away immediately. This leads me to believe there is something about the session recording that's causing this.

EDIT: So with a little more testing, I found out this only happens while the graph is being show and updating real time. If this happens while showing normal parse data (no graph) then it doesnt happen.

**Comment by AterialDawn** [comment]
Fixed on release 10
